package fileutils

import (
	"bufio"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/vilshansen/cipherforge-go/constants"
	"github.com/vilshansen/cipherforge-go/cryptoutils"
	"golang.org/x/crypto/chacha20poly1305"
	"golang.org/x/crypto/hkdf"
)

// deriveSegmentNonce produces a unique 24-byte nonce for a given segment using
// HKDF-SHA256 (RFC 5869), as recommended by NIST SP 800-56C.
//
// Why not XOR?
// XOR-based derivation has two weaknesses:
//  1. Identity at zero: when segmentCounter == 0, XOR is a no-op, so the
//     master nonce itself becomes a live encryption nonce.
//  2. Predictable linear structure: knowing any two (counter, nonce) pairs
//     trivially reveals the master nonce, reducing the search space.
//
// HKDF is a one-way PRF: given any number of derived nonces and their
// counters, the master nonce remains computationally hidden. It also has no
// identity-at-zero property, and is standardised for exactly this use case
// (deriving independent, domain-separated values from a shared secret).
//
// Construction:
//   - IKM  (input key material): masterNonce — already uniformly random, so
//     no salt is needed (HKDF treats a nil salt as a zero-filled string of
//     the hash output length, which is fine when the IKM is already uniform).
//   - Info: the 8-byte big-endian segment counter, which domain-separates
//     each segment so every counter value yields an independent output.
func deriveSegmentNonce(masterNonce []byte, segmentCounter uint64) ([]byte, error) {
	var counterBuf [8]byte
	binary.BigEndian.PutUint64(counterBuf[:], segmentCounter)

	// hkdf.New(hash, ikm, salt, info): salt=nil is safe here because masterNonce
	// is already uniformly random (generated by crypto/rand).
	r := hkdf.New(sha256.New, masterNonce, nil, counterBuf[:])

	nonce := make([]byte, constants.XNonceSize)
	if _, err := io.ReadFull(r, nonce); err != nil {
		// io.ReadFull on an hkdf.Reader only fails if the requested output
		// length exceeds 255 * HashLen (8160 bytes for SHA-256). 24 bytes is
		// nowhere near that limit, so this is a programming-error guard only.
		return nil, fmt.Errorf("failed to derive segment nonce: %w", err)
	}
	return nonce, nil
}

// computeTrailerHMAC produces HMAC-SHA256(macKey, salt || masterNonce || segmentCount).
//
// Committing to segmentCount in the HMAC means any truncation or appending of
// segments changes the count and therefore invalidates the tag, providing
// file-level integrity that per-segment AEAD alone cannot guarantee.
func computeTrailerHMAC(macKey, salt, masterNonce []byte, segmentCount uint64) ([]byte, error) {
	h := hmac.New(sha256.New, macKey)
	h.Write(salt)
	h.Write(masterNonce)
	var countBuf [8]byte
	binary.BigEndian.PutUint64(countBuf[:], segmentCount)
	h.Write(countBuf[:])
	return h.Sum(nil), nil
}

// EncryptFile reads a plaintext file and writes an encrypted version in segments.
func EncryptFile(inputFile, outputFile string, userPassword []byte) error {
	inFile, err := os.Open(inputFile)
	if err != nil {
		return fmt.Errorf("unable to open input file: %w", err)
	}
	defer inFile.Close()

	// 0600 ensures only the current user can read/write the encrypted file.
	outFile, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("unable to create output file: %w", err)
	}

	// Track whether the function succeeds so we can clean up a partial output
	// file on any error path. Without this, a failed encryption leaves a
	// truncated ciphertext on disk, and a failed decryption can leak partial
	// plaintext.
	succeeded := false
	defer func() {
		outFile.Close()
		if !succeeded {
			os.Remove(outputFile)
		}
	}()

	salt, err := cryptoutils.GenerateSalt()
	if err != nil {
		return fmt.Errorf("error generating salt: %w", err)
	}

	// Generate a Master Nonce for this file.
	masterNonce, err := cryptoutils.GenerateNonce()
	if err != nil {
		return fmt.Errorf("error generating master nonce: %w", err)
	}

	// Derive both keys from a single Argon2id invocation:
	//   encKey: XChaCha20-Poly1305 encryption key (bytes 0–31)
	//   macKey: HMAC-SHA256 key for the file trailer (bytes 32–63)
	encKey, macKey := cryptoutils.DeriveKeys(userPassword, salt)
	defer cryptoutils.ZeroBytes(encKey)
	defer cryptoutils.ZeroBytes(macKey)

	aead, err := chacha20poly1305.NewX(encKey)
	if err != nil {
		return fmt.Errorf("unable to initialise XChaCha20-Poly1305: %w", err)
	}

	// Wrap both files in bufio to reduce syscall overhead. The buffer is sized
	// to one full segment plus framing so a typical iteration is one read and
	// one write syscall.
	bufIn := bufio.NewReaderSize(inFile, constants.SegmentSize)
	bufOut := bufio.NewWriterSize(outFile, constants.SegmentSize+aead.Overhead()+8)
	// Flush must happen before the deferred outFile.Close().
	defer bufOut.Flush()

	// Write magic bytes and version into the file header.
	// Magic allows fast rejection of non-.cfo files before key derivation.
	// Version enables forward-compatible format detection.
	if _, err := bufOut.Write([]byte(constants.Magic)); err != nil {
		return fmt.Errorf("error writing magic header: %w", err)
	}
	var versionBuf [4]byte
	binary.BigEndian.PutUint32(versionBuf[:], constants.FileVersion)
	if _, err := bufOut.Write(versionBuf[:]); err != nil {
		return fmt.Errorf("error writing version header: %w", err)
	}

	// Write salt and master nonce into the file header.
	if _, err := bufOut.Write(salt); err != nil {
		return fmt.Errorf("error writing salt header: %w", err)
	}
	if _, err := bufOut.Write(masterNonce); err != nil {
		return fmt.Errorf("error writing nonce header: %w", err)
	}

	fileInfo, _ := inFile.Stat()
	totalBytes := fileInfo.Size()
	prefix := fmt.Sprintf("Encrypting %s", filepath.Base(inputFile))

	// Reusable buffers: hoisted outside the loop to avoid per-segment allocation.
	plaintextBuf := make([]byte, constants.SegmentSize)
	ciphertextBuf := make([]byte, 0, constants.SegmentSize+aead.Overhead())
	aad := make([]byte, 16)
	var lenBuf [8]byte

	var segmentCount uint64
	var bytesDone int64

	for {
		// io.ReadFull guarantees a full SegmentSize read or a clean short read
		// on the final segment (io.ErrUnexpectedEOF). A plain Read may return
		// fewer bytes than requested even mid-file, which would silently produce
		// undersized segments.
		n, err := io.ReadFull(bufIn, plaintextBuf)
		if n > 0 {
			// Derive a unique nonce for this segment via HKDF-SHA256(ikm=masterNonce, info=counter).
			// This is a one-way derivation: no identity-at-zero, no linear structure.
			nonce, nonceErr := deriveSegmentNonce(masterNonce, segmentCount)
			if nonceErr != nil {
				return fmt.Errorf("error deriving segment nonce: %w", nonceErr)
			}

			// AAD binds the segment index and the plaintext length to the ciphertext.
			// Storing the plaintext length explicitly (rather than computing it from
			// len(ciphertext)-Overhead() during decryption) makes the AAD self-contained
			// and robust to future changes in the AEAD implementation.
			binary.BigEndian.PutUint64(aad[:8], segmentCount)
			binary.BigEndian.PutUint64(aad[8:], uint64(n))

			ciphertextBuf = aead.Seal(ciphertextBuf[:0], nonce, plaintextBuf[:n], aad)

			// Write Segment Structure: [Length (8B)][Ciphertext + Tag]
			binary.BigEndian.PutUint64(lenBuf[:], uint64(len(ciphertextBuf)))
			if _, err := bufOut.Write(lenBuf[:]); err != nil {
				return fmt.Errorf("error writing segment length: %w", err)
			}
			if _, err := bufOut.Write(ciphertextBuf); err != nil {
				return fmt.Errorf("error writing ciphertext: %w", err)
			}

			segmentCount++
			bytesDone += int64(n)
			if totalBytes > 0 {
				cryptoutils.RunProgressBar(prefix, int((bytesDone*100)/totalBytes))
			}
		}

		if err == io.EOF || err == io.ErrUnexpectedEOF {
			// io.EOF: zero bytes read, clean end of file.
			// io.ErrUnexpectedEOF: partial final segment, already processed above.
			break
		}
		if err != nil {
			return fmt.Errorf("error reading input: %w", err)
		}
	}

	// Write the file trailer: segmentCount (8B) || HMAC-SHA256(macKey, salt ||
	// masterNonce || segmentCount).
	//
	// Storing segmentCount explicitly in the trailer eliminates the need for a
	// pre-decryption scanning pass: the decoder reads the count directly,
	// verifies the HMAC, and proceeds in a single sequential pass.
	//
	// The HMAC authenticates the header fields and the total number of segments,
	// preventing three attacks that per-segment AEAD alone cannot stop:
	//   1. Header substitution: swapping the salt or master nonce from another
	//      file encrypted with the same password would cause silent decryption
	//      to wrong plaintext. The HMAC binds both header fields to this specific
	//      ciphertext.
	//   2. File-level truncation: removing trailing segments changes segmentCount,
	//      invalidating the HMAC before any segment is decrypted.
	//   3. Segment appending: adding segments from another file also changes
	//      segmentCount, invalidating the HMAC.
	//
	// The macKey is independent of encKey (derived from Argon2id bytes 32–63),
	// so compromising one key does not compromise the other.
	binary.BigEndian.PutUint64(lenBuf[:], segmentCount)
	if _, err := bufOut.Write(lenBuf[:]); err != nil {
		return fmt.Errorf("error writing segment count: %w", err)
	}

	trailer, err := computeTrailerHMAC(macKey, salt, masterNonce, segmentCount)
	if err != nil {
		return fmt.Errorf("error computing trailer HMAC: %w", err)
	}
	if _, err := bufOut.Write(trailer); err != nil {
		return fmt.Errorf("error writing trailer: %w", err)
	}

	cryptoutils.RunProgressBar(prefix, 100)
	fmt.Println()

	succeeded = true
	return nil
}

// DecryptFile reads an encrypted file and restores the original plaintext.
func DecryptFile(inputFile, outputFile string, userPassword []byte) error {
	inFile, err := os.Open(inputFile)
	if err != nil {
		return fmt.Errorf("unable to open input file: %w", err)
	}
	defer inFile.Close()

	outFile, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("unable to create output file: %w", err)
	}

	// Remove the output file on any failure to prevent partial plaintext leaking
	// to disk. This is especially important for decryption: if authentication
	// fails mid-file, whatever plaintext was written before detection must not
	// persist.
	succeeded := false
	defer func() {
		outFile.Close()
		if !succeeded {
			os.Remove(outputFile)
		}
	}()

	// 1. Read and validate magic bytes.
	// Reject non-.cfo files immediately, before any expensive key derivation.
	magicBuf := make([]byte, constants.MagicSize)
	if _, err := io.ReadFull(inFile, magicBuf); err != nil {
		return fmt.Errorf("error reading magic header: %w", err)
	}
	if string(magicBuf) != constants.Magic {
		return fmt.Errorf("not a valid .cfo file")
	}

	// 2. Read and validate the format version.
	var versionBuf [4]byte
	if _, err := io.ReadFull(inFile, versionBuf[:]); err != nil {
		return fmt.Errorf("error reading version header: %w", err)
	}
	fileVersion := binary.BigEndian.Uint32(versionBuf[:])
	if fileVersion != constants.FileVersion {
		return fmt.Errorf("unsupported file format version %d (expected %d)", fileVersion, constants.FileVersion)
	}

	// 3. Read Salt
	salt := make([]byte, constants.SaltSize)
	if _, err := io.ReadFull(inFile, salt); err != nil {
		return fmt.Errorf("error reading salt: %w", err)
	}

	// 4. Read Master Nonce
	masterNonce := make([]byte, constants.XNonceSize)
	if _, err := io.ReadFull(inFile, masterNonce); err != nil {
		return fmt.Errorf("error reading master nonce: %w", err)
	}

	// Derive both keys from a single Argon2id invocation.
	encKey, macKey := cryptoutils.DeriveKeys(userPassword, salt)
	defer cryptoutils.ZeroBytes(encKey)
	defer cryptoutils.ZeroBytes(macKey)

	aead, err := chacha20poly1305.NewX(encKey)
	if err != nil {
		return fmt.Errorf("unable to initialise XChaCha20-Poly1305: %w", err)
	}

	// 5. Verify the file trailer BEFORE decrypting any segment.
	//
	// The trailer is the last TrailerSize bytes of the file. It contains
	// segmentCount (8B) || HMAC-SHA256(macKey, salt || masterNonce ||
	// segmentCount). Verifying it here provides file-level authentication
	// that covers the header fields and segment count, which per-segment
	// AEAD alone cannot protect:
	//   - A wrong password will produce a wrong macKey, failing immediately
	//     here rather than after streaming the entire payload.
	//   - Header substitution, file truncation, and segment appending are all
	//     detected before a single byte of plaintext is written.
	fileInfo, _ := inFile.Stat()
	totalFileSize := fileInfo.Size()

	if totalFileSize < int64(constants.MagicSize+constants.VersionSize+constants.SaltSize+constants.XNonceSize+constants.TrailerSize) {
		return fmt.Errorf("file too small to be a valid .cfo file")
	}

	// Read the trailer from the end of the file using ReadAt so we do not
	// disturb the sequential read position.
	trailerOffset := totalFileSize - int64(constants.TrailerSize)
	trailerBuf := make([]byte, constants.TrailerSize)
	if _, err := inFile.ReadAt(trailerBuf, trailerOffset); err != nil {
		return fmt.Errorf("error reading trailer: %w", err)
	}

	// TrailerSize = 8 (segmentCount) + HMACSize (32). Parse them out.
	segmentCount := binary.BigEndian.Uint64(trailerBuf[:8])
	storedHMAC := trailerBuf[8:]

	// Compute the expected HMAC and compare in constant time.
	expectedHMAC, err := computeTrailerHMAC(macKey, salt, masterNonce, segmentCount)
	if err != nil {
		return fmt.Errorf("error computing trailer HMAC: %w", err)
	}
	if !hmac.Equal(storedHMAC, expectedHMAC) {
		return fmt.Errorf("authentication failed: wrong password or file is corrupt")
	}

	// 6. Trailer verified. Proceed with a single sequential decryption pass.
	// Wrap both files in bufio; inFile is already positioned just past the
	// header from the ReadFull calls above.
	bufIn := bufio.NewReaderSize(inFile, constants.SegmentSize+aead.Overhead()+8)
	bufOut := bufio.NewWriterSize(outFile, constants.SegmentSize)
	defer bufOut.Flush()

	prefix := fmt.Sprintf("Decrypting %s", filepath.Base(inputFile))
	var bytesRead uint64
	bytesRead += uint64(constants.MagicSize + constants.VersionSize + constants.SaltSize + constants.XNonceSize)
	totalBytes := uint64(totalFileSize)

	// Reusable buffers: hoisted outside the loop to avoid per-segment allocation.
	ciphertextBuf := make([]byte, constants.SegmentSize+aead.Overhead())
	sizeBuf := make([]byte, 8)
	aad := make([]byte, 16)

	for i := uint64(0); i < segmentCount; i++ {
		// 7. Read segment length.
		if _, err := io.ReadFull(bufIn, sizeBuf); err != nil {
			return fmt.Errorf("error reading segment length: %w", err)
		}
		bytesRead += 8

		segmentLen := binary.BigEndian.Uint64(sizeBuf)

		// OOM guard: reject any segment length that exceeds the maximum
		// possible ciphertext size (plaintext SegmentSize + AEAD overhead).
		if segmentLen > uint64(constants.SegmentSize+aead.Overhead()) {
			return fmt.Errorf("corrupt segment: length field exceeds maximum allowed size")
		}

		// Read directly into the pre-allocated buffer, avoiding a per-segment
		// heap allocation.
		if _, err := io.ReadFull(bufIn, ciphertextBuf[:segmentLen]); err != nil {
			return fmt.Errorf("error reading ciphertext: %w", err)
		}
		bytesRead += segmentLen

		// 8. Derive unique nonce for this segment — must mirror the encryption path.
		nonce, err := deriveSegmentNonce(masterNonce, i)
		if err != nil {
			return fmt.Errorf("error deriving segment nonce: %w", err)
		}

		// 9. Reconstruct AAD for authentication.
		plaintextLen := segmentLen - uint64(aead.Overhead())
		binary.BigEndian.PutUint64(aad[:8], i)
		binary.BigEndian.PutUint64(aad[8:], plaintextLen)

		// Decrypt in-place: Open writes plaintext back into ciphertextBuf,
		// which is safe because ciphertextBuf is at least SegmentSize bytes.
		plaintextSegment, err := aead.Open(ciphertextBuf[:0], nonce, ciphertextBuf[:segmentLen], aad)
		if err != nil {
			// This should not be reachable given the trailer HMAC already passed,
			// but is retained as a defence-in-depth layer.
			return fmt.Errorf("authentication failed: wrong password or file is corrupt")
		}

		if _, err := bufOut.Write(plaintextSegment); err != nil {
			return fmt.Errorf("error writing plaintext: %w", err)
		}

		bytesRead += uint64(len(plaintextSegment))
		if totalBytes > 0 {
			cryptoutils.RunProgressBar(prefix, int((bytesRead*100)/totalBytes))
		}
	}

	cryptoutils.RunProgressBar(prefix, 100)
	fmt.Println()

	succeeded = true
	return nil
}

// ExpandInputPaths resolves multiple input paths and glob patterns,
// and filters out directories. Files that do not match the expected extension
// for the given operation are skipped with a warning rather than silently,
// so the user is never left wondering why a file was ignored.
func ExpandInputPaths(inputs []string, operation string) ([]string, error) {
	var files []string

	for _, input := range inputs {
		// Step 1: check if input is a literal file path.
		info, err := os.Stat(input)
		if err == nil {
			if !info.IsDir() {
				ext := strings.ToLower(filepath.Ext(info.Name()))
				// Parentheses make the compound condition explicit and unambiguous.
				// Without them the precedence of && vs || is easy to misread.
				if (operation == "encrypt" && ext != ".cfo") || (operation == "decrypt" && ext == ".cfo") {
					files = append(files, input)
				} else {
					// Warn rather than silently skip so the user knows the file
					// was seen but excluded.
					fmt.Fprintf(os.Stderr, "warning: skipping %q — not a valid target for %s\n", input, operation)
				}
			}
			continue
		}

		// Step 2: treat as glob pattern if the literal path does not exist.
		matches, err := filepath.Glob(input)
		if err != nil {
			return nil, fmt.Errorf("invalid pattern %q: %w", input, err)
		}

		if len(matches) == 0 {
			fmt.Fprintf(os.Stderr, "warning: pattern %q matched no files\n", input)
			continue
		}

		for _, match := range matches {
			info, err := os.Stat(match)
			if err != nil {
				continue
			}
			if !info.IsDir() {
				ext := strings.ToLower(filepath.Ext(info.Name()))
				if (operation == "encrypt" && ext != ".cfo") || (operation == "decrypt" && ext == ".cfo") {
					files = append(files, match)
				} else {
					fmt.Fprintf(os.Stderr, "warning: skipping %q — not a valid target for %s\n", match, operation)
				}
			}
		}
	}

	if len(files) == 0 {
		return nil, fmt.Errorf("no valid input files found")
	}

	return files, nil
}
