package fileutils

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/vilshansen/cipherforge-go/constants"
	"github.com/vilshansen/cipherforge-go/cryptoutils"
	"golang.org/x/crypto/chacha20poly1305"
	"golang.org/x/crypto/hkdf"
)

// deriveSegmentNonce produces a unique 24-byte nonce for a given segment using
// HKDF-SHA256 (RFC 5869), as recommended by NIST SP 800-56C.
//
// Why not XOR?
// XOR-based derivation has two weaknesses:
//  1. Identity at zero: when segmentCounter == 0, XOR is a no-op, so the
//     master nonce itself becomes a live encryption nonce.
//  2. Predictable linear structure: knowing any two (counter, nonce) pairs
//     trivially reveals the master nonce, reducing the search space.
//
// HKDF is a one-way PRF: given any number of derived nonces and their
// counters, the master nonce remains computationally hidden. It also has no
// identity-at-zero property, and is standardised for exactly this use case
// (deriving independent, domain-separated values from a shared secret).
//
// Construction:
//   - IKM  (input key material): masterNonce — already uniformly random, so
//     no salt is needed (HKDF treats a nil salt as a zero-filled string of
//     the hash output length, which is fine when the IKM is already uniform).
//   - Info: the 8-byte big-endian segment counter, which domain-separates
//     each segment so every counter value yields an independent output.
func deriveSegmentNonce(masterNonce []byte, segmentCounter uint64) ([]byte, error) {
	var counterBuf [8]byte
	binary.BigEndian.PutUint64(counterBuf[:], segmentCounter)

	// hkdf.New(hash, ikm, salt, info): salt=nil is safe here because masterNonce
	// is already uniformly random (generated by crypto/rand).
	r := hkdf.New(sha256.New, masterNonce, nil, counterBuf[:])

	nonce := make([]byte, constants.XNonceSize)
	if _, err := io.ReadFull(r, nonce); err != nil {
		// io.ReadFull on an hkdf.Reader only fails if the requested output
		// length exceeds 255 * HashLen (8160 bytes for SHA-256). 24 bytes is
		// nowhere near that limit, so this is a programming-error guard only.
		return nil, fmt.Errorf("failed to derive segment nonce: %w", err)
	}
	return nonce, nil
}

// EncryptFile reads a plaintext file and writes an encrypted version in segments.
func EncryptFile(inputFile, outputFile string, userPassword []byte) error {
	inFile, err := os.Open(inputFile)
	if err != nil {
		return fmt.Errorf("unable to open input file: %w", err)
	}
	defer inFile.Close()

	// 0600 ensures only the current user can read/write the encrypted file.
	outFile, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("unable to create output file: %w", err)
	}

	// Track whether the function succeeds so we can clean up a partial output
	// file on any error path. Without this, a failed encryption leaves a
	// truncated ciphertext on disk, and a failed decryption can leak partial
	// plaintext.
	succeeded := false
	defer func() {
		outFile.Close()
		if !succeeded {
			os.Remove(outputFile)
		}
	}()

	salt, err := cryptoutils.GenerateSalt()
	if err != nil {
		return fmt.Errorf("error generating salt: %w", err)
	}

	// Write salt first for key derivation.
	if _, err := outFile.Write(salt); err != nil {
		return fmt.Errorf("error writing salt header: %w", err)
	}

	// Generate a Master Nonce for this file.
	masterNonce, err := cryptoutils.GenerateNonce()
	if err != nil {
		return fmt.Errorf("error generating master nonce: %w", err)
	}

	// Write the Master Nonce to the file header.
	if _, err := outFile.Write(masterNonce); err != nil {
		return fmt.Errorf("error writing nonce header: %w", err)
	}

	key := cryptoutils.DeriveKey(userPassword, salt)
	defer cryptoutils.ZeroBytes(key) // Wipe key from RAM after use.

	aead, err := chacha20poly1305.NewX(key)
	if err != nil {
		return fmt.Errorf("unable to initialise XChaCha20-Poly1305: %w", err)
	}

	fileInfo, _ := inFile.Stat()
	totalBytes := fileInfo.Size()
	prefix := fmt.Sprintf("Encrypting %s", filepath.Base(inputFile))

	plaintextBuf := make([]byte, constants.SegmentSize)
	var segmentCounter uint64
	var bytesDone int64

	for {
		n, readErr := inFile.Read(plaintextBuf)
		if n == 0 {
			break
		}

		// Derive a unique nonce for this segment via HKDF-SHA256(ikm=masterNonce, info=counter).
		// This is a one-way derivation: no identity-at-zero, no linear structure.
		nonce, err := deriveSegmentNonce(masterNonce, segmentCounter)
		if err != nil {
			return fmt.Errorf("error deriving segment nonce: %w", err)
		}

		// AAD binds the segment index and the plaintext length to the ciphertext.
		// Storing the plaintext length explicitly (rather than computing it from
		// len(ciphertext)-Overhead() during decryption) makes the AAD self-contained
		// and robust to future changes in the AEAD implementation.
		aad := make([]byte, 16)
		binary.BigEndian.PutUint64(aad[:8], segmentCounter)
		binary.BigEndian.PutUint64(aad[8:], uint64(n)) // plaintext segment length

		ciphertext := aead.Seal(nil, nonce, plaintextBuf[:n], aad)

		// Write Segment Structure: [Length (8B)][Ciphertext + Tag]
		if err := binary.Write(outFile, binary.BigEndian, uint64(len(ciphertext))); err != nil {
			return fmt.Errorf("error writing segment length: %w", err)
		}
		if _, err := outFile.Write(ciphertext); err != nil {
			return fmt.Errorf("error writing ciphertext: %w", err)
		}

		segmentCounter++
		bytesDone += int64(n)

		if totalBytes > 0 {
			cryptoutils.RunProgressBar(prefix, int((bytesDone*100)/totalBytes))
		}

		if readErr == io.EOF {
			break
		}
	}

	cryptoutils.RunProgressBar(prefix, 100)
	fmt.Println()

	succeeded = true
	return nil
}

// DecryptFile reads an encrypted file and restores the original plaintext.
func DecryptFile(inputFile, outputFile string, userPassword []byte) error {
	inFile, err := os.Open(inputFile)
	if err != nil {
		return fmt.Errorf("unable to open input file: %w", err)
	}
	defer inFile.Close()

	outFile, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("unable to create output file: %w", err)
	}

	// Remove the output file on any failure to prevent partial plaintext leaking
	// to disk. This is especially important for decryption: if authentication
	// fails mid-file, whatever plaintext was written before detection must not
	// persist.
	succeeded := false
	defer func() {
		outFile.Close()
		if !succeeded {
			os.Remove(outputFile)
		}
	}()

	// 1. Read Salt
	salt := make([]byte, constants.SaltSize)
	if _, err := io.ReadFull(inFile, salt); err != nil {
		return fmt.Errorf("error reading salt: %w", err)
	}

	// 2. Read Master Nonce
	masterNonce := make([]byte, constants.XNonceSize)
	if _, err := io.ReadFull(inFile, masterNonce); err != nil {
		return fmt.Errorf("error reading master nonce: %w", err)
	}

	key := cryptoutils.DeriveKey(userPassword, salt)
	defer cryptoutils.ZeroBytes(key)

	aead, err := chacha20poly1305.NewX(key)
	if err != nil {
		return fmt.Errorf("unable to initialise XChaCha20-Poly1305: %w", err)
	}

	fileInfo, _ := inFile.Stat()
	totalBytes := uint64(fileInfo.Size())
	prefix := fmt.Sprintf("Decrypting %s", filepath.Base(inputFile))

	var segmentCounter uint64
	var bytesRead uint64
	bytesRead += uint64(constants.SaltSize + constants.XNonceSize)

	sizeBuf := make([]byte, 8)

	for {
		// 3. Read segment length
		if _, err := io.ReadFull(inFile, sizeBuf); err != nil {
			if err == io.EOF {
				break
			}
			return fmt.Errorf("error reading segment length: %w", err)
		}
		bytesRead += 8

		segmentLen := binary.BigEndian.Uint64(sizeBuf)

		// SECURITY: Prevent OOM attacks by validating segment length before
		// allocating. The maximum legitimate ciphertext length is SegmentSize
		// (plaintext) + Overhead() (Poly1305 tag = 16 bytes).
		maxAllowed := uint64(constants.SegmentSize + aead.Overhead())
		if segmentLen > maxAllowed {
			return fmt.Errorf("security error: segment size %d exceeds limit", segmentLen)
		}

		ciphertext := make([]byte, segmentLen)
		if _, err := io.ReadFull(inFile, ciphertext); err != nil {
			return fmt.Errorf("error reading ciphertext: %w", err)
		}
		bytesRead += segmentLen

		// 4. Derive unique nonce for this segment — must mirror the encryption path.
		nonce, err := deriveSegmentNonce(masterNonce, segmentCounter)
		if err != nil {
			return fmt.Errorf("error deriving segment nonce: %w", err)
		}

		// 5. Reconstruct AAD for authentication.
		//
		// The plaintext length is derived from the ciphertext length by subtracting
		// the AEAD tag size. This is safe because:
		//   a) segmentLen has already been bounds-checked above (≤ SegmentSize + Overhead),
		//      so the subtraction cannot underflow a legitimate segment.
		//   b) The AEAD authentication step immediately below will reject any segment
		//      whose AAD does not match what was used during encryption, catching any
		//      mismatch before plaintext is written.
		//
		// Note: this derivation mirrors what EncryptFile wrote into the AAD:
		//   binary.BigEndian.PutUint64(aad[8:], uint64(n))  // plaintext length = len(ciphertext) - Overhead()
		plaintextLen := uint64(len(ciphertext)) - uint64(aead.Overhead())
		aad := make([]byte, 16)
		binary.BigEndian.PutUint64(aad[:8], segmentCounter)
		binary.BigEndian.PutUint64(aad[8:], plaintextLen)

		plaintextSegment, err := aead.Open(nil, nonce, ciphertext, aad)
		if err != nil {
			return fmt.Errorf("authentication failed: tampering detected or wrong password")
		}

		if _, err := outFile.Write(plaintextSegment); err != nil {
			return fmt.Errorf("error writing plaintext: %w", err)
		}

		segmentCounter++

		if totalBytes > 0 {
			cryptoutils.RunProgressBar(prefix, int((bytesRead*100)/totalBytes))
		}
	}

	cryptoutils.RunProgressBar(prefix, 100)
	fmt.Println()

	succeeded = true
	return nil
}

// ExpandInputPaths resolves multiple input paths and glob patterns,
// and filters out directories. Files that do not match the expected extension
// for the given operation are skipped with a warning rather than silently,
// so the user is never left wondering why a file was ignored.
func ExpandInputPaths(inputs []string, operation string) ([]string, error) {
	var files []string

	for _, input := range inputs {
		// Step 1: check if input is a literal file path.
		info, err := os.Stat(input)
		if err == nil {
			if !info.IsDir() {
				ext := strings.ToLower(filepath.Ext(info.Name()))
				// Parentheses make the compound condition explicit and unambiguous.
				// Without them the precedence of && vs || is easy to misread.
				if (operation == "encrypt" && ext != ".cfo") || (operation == "decrypt" && ext == ".cfo") {
					files = append(files, input)
				} else {
					// Warn rather than silently skip so the user knows the file
					// was seen but excluded.
					fmt.Fprintf(os.Stderr, "warning: skipping %q (wrong extension for %s)\n", input, operation)
				}
			}
			continue
		}

		// Step 2: treat as glob pattern if the literal path does not exist.
		matches, err := filepath.Glob(input)
		if err != nil {
			return nil, fmt.Errorf("invalid pattern %q: %w", input, err)
		}

		if len(matches) == 0 {
			fmt.Fprintf(os.Stderr, "warning: pattern %q matched no files\n", input)
			continue
		}

		for _, match := range matches {
			info, err := os.Stat(match)
			if err != nil {
				continue
			}
			if !info.IsDir() {
				ext := strings.ToLower(filepath.Ext(info.Name()))
				if (operation == "encrypt" && ext != ".cfo") || (operation == "decrypt" && ext == ".cfo") {
					files = append(files, match)
				} else {
					fmt.Fprintf(os.Stderr, "warning: skipping %q (wrong extension for %s)\n", match, operation)
				}
			}
		}
	}

	if len(files) == 0 {
		return nil, fmt.Errorf("no valid input files found")
	}

	return files, nil
}