package fileutils

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/vilshansen/cipherforge-go/constants"
	"github.com/vilshansen/cipherforge-go/cryptoutils"
	"golang.org/x/crypto/chacha20poly1305"
	"golang.org/x/crypto/hkdf"
)

// deriveSegmentNonce produces a unique 24-byte nonce for a given segment using
// HKDF-SHA256 (RFC 5869), as recommended by NIST SP 800-56C.
//
// Why not XOR?
// XOR-based derivation has two weaknesses:
//  1. Identity at zero: when segmentCounter == 0, XOR is a no-op, so the
//     master nonce itself becomes a live encryption nonce.
//  2. Predictable linear structure: knowing any two (counter, nonce) pairs
//     trivially reveals the master nonce, reducing the search space.
//
// HKDF is a one-way PRF: given any number of derived nonces and their
// counters, the master nonce remains computationally hidden. It also has no
// identity-at-zero property, and is standardised for exactly this use case
// (deriving independent, domain-separated values from a shared secret).
//
// Construction:
//   - IKM  (input key material): masterNonce — already uniformly random, so
//     no salt is needed (HKDF treats a nil salt as a zero-filled string of
//     the hash output length, which is fine when the IKM is already uniform).
//   - Info: the 8-byte big-endian segment counter, which domain-separates
//     each segment so every counter value yields an independent output.
func deriveSegmentNonce(masterNonce []byte, segmentCounter uint64) ([]byte, error) {
	var counterBuf [8]byte
	binary.BigEndian.PutUint64(counterBuf[:], segmentCounter)

	// hkdf.New(hash, ikm, salt, info): salt=nil is safe here because masterNonce
	// is already uniformly random (generated by crypto/rand).
	r := hkdf.New(sha256.New, masterNonce, nil, counterBuf[:])

	nonce := make([]byte, constants.XNonceSize)
	if _, err := io.ReadFull(r, nonce); err != nil {
		// io.ReadFull on an hkdf.Reader only fails if the requested output
		// length exceeds 255 * HashLen (8160 bytes for SHA-256). 24 bytes is
		// nowhere near that limit, so this is a programming-error guard only.
		return nil, fmt.Errorf("failed to derive segment nonce: %w", err)
	}
	return nonce, nil
}

// computeTrailerHMAC produces HMAC-SHA256(macKey, salt || masterNonce || segmentCount).
//
// Committing to segmentCount in the HMAC means any truncation or appending of
// segments changes the count and therefore invalidates the tag, providing
// file-level integrity that per-segment AEAD alone cannot guarantee.
func computeTrailerHMAC(macKey, salt, masterNonce []byte, segmentCount uint64) ([]byte, error) {
	h := hmac.New(sha256.New, macKey)
	h.Write(salt)
	h.Write(masterNonce)
	var countBuf [8]byte
	binary.BigEndian.PutUint64(countBuf[:], segmentCount)
	h.Write(countBuf[:])
	return h.Sum(nil), nil
}

// EncryptFile reads a plaintext file and writes an encrypted version in segments.
func EncryptFile(inputFile, outputFile string, userPassword []byte) error {
	inFile, err := os.Open(inputFile)
	if err != nil {
		return fmt.Errorf("unable to open input file: %w", err)
	}
	defer inFile.Close()

	// 0600 ensures only the current user can read/write the encrypted file.
	outFile, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("unable to create output file: %w", err)
	}

	// Track whether the function succeeds so we can clean up a partial output
	// file on any error path. Without this, a failed encryption leaves a
	// truncated ciphertext on disk, and a failed decryption can leak partial
	// plaintext.
	succeeded := false
	defer func() {
		outFile.Close()
		if !succeeded {
			os.Remove(outputFile)
		}
	}()

	salt, err := cryptoutils.GenerateSalt()
	if err != nil {
		return fmt.Errorf("error generating salt: %w", err)
	}

	// Write salt first for key derivation.
	if _, err := outFile.Write(salt); err != nil {
		return fmt.Errorf("error writing salt header: %w", err)
	}

	// Generate a Master Nonce for this file.
	masterNonce, err := cryptoutils.GenerateNonce()
	if err != nil {
		return fmt.Errorf("error generating master nonce: %w", err)
	}

	// Write the Master Nonce to the file header.
	if _, err := outFile.Write(masterNonce); err != nil {
		return fmt.Errorf("error writing nonce header: %w", err)
	}

	// Derive both keys from a single Argon2id invocation:
	//   encKey: XChaCha20-Poly1305 encryption key (bytes 0–31)
	//   macKey: HMAC-SHA256 key for the file trailer (bytes 32–63)
	encKey, macKey := cryptoutils.DeriveKeys(userPassword, salt)
	defer cryptoutils.ZeroBytes(encKey)
	defer cryptoutils.ZeroBytes(macKey)

	aead, err := chacha20poly1305.NewX(encKey)
	if err != nil {
		return fmt.Errorf("unable to initialise XChaCha20-Poly1305: %w", err)
	}

	fileInfo, _ := inFile.Stat()
	totalBytes := fileInfo.Size()
	prefix := fmt.Sprintf("Encrypting %s", filepath.Base(inputFile))

	plaintextBuf := make([]byte, constants.SegmentSize)
	var segmentCounter uint64
	var bytesDone int64

	for {
		n, readErr := inFile.Read(plaintextBuf)
		if n == 0 {
			break
		}

		// Derive a unique nonce for this segment via HKDF-SHA256(ikm=masterNonce, info=counter).
		// This is a one-way derivation: no identity-at-zero, no linear structure.
		nonce, err := deriveSegmentNonce(masterNonce, segmentCounter)
		if err != nil {
			return fmt.Errorf("error deriving segment nonce: %w", err)
		}

		// AAD binds the segment index and the plaintext length to the ciphertext.
		// Storing the plaintext length explicitly (rather than computing it from
		// len(ciphertext)-Overhead() during decryption) makes the AAD self-contained
		// and robust to future changes in the AEAD implementation.
		aad := make([]byte, 16)
		binary.BigEndian.PutUint64(aad[:8], segmentCounter)
		binary.BigEndian.PutUint64(aad[8:], uint64(n)) // plaintext segment length

		ciphertext := aead.Seal(nil, nonce, plaintextBuf[:n], aad)

		// Write Segment Structure: [Length (8B)][Ciphertext + Tag]
		if err := binary.Write(outFile, binary.BigEndian, uint64(len(ciphertext))); err != nil {
			return fmt.Errorf("error writing segment length: %w", err)
		}
		if _, err := outFile.Write(ciphertext); err != nil {
			return fmt.Errorf("error writing ciphertext: %w", err)
		}

		segmentCounter++
		bytesDone += int64(n)

		if totalBytes > 0 {
			cryptoutils.RunProgressBar(prefix, int((bytesDone*100)/totalBytes))
		}

		if readErr == io.EOF {
			break
		}
	}

	// Write the file trailer: HMAC-SHA256(macKey, salt || masterNonce || segmentCount).
	//
	// This authenticates the header fields and the total number of segments,
	// preventing three attacks that per-segment AEAD alone cannot stop:
	//   1. Header substitution: swapping the salt or master nonce from another
	//      file encrypted with the same password would cause silent decryption
	//      to wrong plaintext. The HMAC binds both header fields to this specific
	//      ciphertext.
	//   2. File-level truncation: removing trailing segments changes segmentCount,
	//      invalidating the HMAC before any segment is decrypted.
	//   3. Segment appending: adding segments from another file also changes
	//      segmentCount, invalidating the HMAC.
	//
	// The macKey is independent of encKey (derived from Argon2id bytes 32–63),
	// so compromising one key does not compromise the other.
	trailer, err := computeTrailerHMAC(macKey, salt, masterNonce, segmentCounter)
	if err != nil {
		return fmt.Errorf("error computing trailer HMAC: %w", err)
	}
	if _, err := outFile.Write(trailer); err != nil {
		return fmt.Errorf("error writing trailer: %w", err)
	}

	cryptoutils.RunProgressBar(prefix, 100)
	fmt.Println()

	succeeded = true
	return nil
}

// DecryptFile reads an encrypted file and restores the original plaintext.
func DecryptFile(inputFile, outputFile string, userPassword []byte) error {
	inFile, err := os.Open(inputFile)
	if err != nil {
		return fmt.Errorf("unable to open input file: %w", err)
	}
	defer inFile.Close()

	outFile, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("unable to create output file: %w", err)
	}

	// Remove the output file on any failure to prevent partial plaintext leaking
	// to disk. This is especially important for decryption: if authentication
	// fails mid-file, whatever plaintext was written before detection must not
	// persist.
	succeeded := false
	defer func() {
		outFile.Close()
		if !succeeded {
			os.Remove(outputFile)
		}
	}()

	// 1. Read Salt
	salt := make([]byte, constants.SaltSize)
	if _, err := io.ReadFull(inFile, salt); err != nil {
		return fmt.Errorf("error reading salt: %w", err)
	}

	// 2. Read Master Nonce
	masterNonce := make([]byte, constants.XNonceSize)
	if _, err := io.ReadFull(inFile, masterNonce); err != nil {
		return fmt.Errorf("error reading master nonce: %w", err)
	}

	// Derive both keys from a single Argon2id invocation.
	encKey, macKey := cryptoutils.DeriveKeys(userPassword, salt)
	defer cryptoutils.ZeroBytes(encKey)
	defer cryptoutils.ZeroBytes(macKey)

	aead, err := chacha20poly1305.NewX(encKey)
	if err != nil {
		return fmt.Errorf("unable to initialise XChaCha20-Poly1305: %w", err)
	}

	// 3. Verify the file trailer BEFORE decrypting any segment.
	//
	// The trailer is the last TrailerSize bytes of the file. It contains
	// HMAC-SHA256(macKey, salt || masterNonce || segmentCount). Verifying it
	// here provides file-level authentication that covers the header fields
	// and segment count, which per-segment AEAD alone cannot protect:
	//   - A wrong password will produce a wrong macKey, failing immediately
	//     here rather than after streaming the entire payload.
	//   - Header substitution, file truncation, and segment appending are all
	//     detected before a single byte of plaintext is written.
	fileInfo, _ := inFile.Stat()
	totalFileSize := fileInfo.Size()

	if totalFileSize < int64(constants.SaltSize+constants.XNonceSize+constants.TrailerSize) {
		return fmt.Errorf("file too small to be a valid .cfo file")
	}

	// Read the trailer from the end of the file.
	trailerOffset := totalFileSize - int64(constants.TrailerSize)
	storedTrailer := make([]byte, constants.TrailerSize)
	if _, err := inFile.ReadAt(storedTrailer, trailerOffset); err != nil {
		return fmt.Errorf("error reading trailer: %w", err)
	}

	// The segment count is embedded in the last 8 bytes of the HMAC input,
	// but we don't know it yet — we need to count segments to verify. Instead
	// we stream the payload region once to count segments, verify the HMAC,
	// then seek back to decrypt. This is a single extra linear pass with no
	// additional memory beyond what we already use per segment.
	payloadSize := trailerOffset - int64(constants.SaltSize+constants.XNonceSize)
	var segmentCount uint64
	var scanned int64
	scanBuf := make([]byte, 8)

	for scanned < payloadSize {
		if _, err := io.ReadFull(inFile, scanBuf); err != nil {
			return fmt.Errorf("error scanning segment lengths: %w", err)
		}
		scanned += 8
		segLen := binary.BigEndian.Uint64(scanBuf)

		maxAllowed := uint64(constants.SegmentSize + aead.Overhead())
		if segLen > maxAllowed {
			return fmt.Errorf("security error: segment size %d exceeds limit", segLen)
		}

		// Skip the ciphertext bytes without reading them into memory.
		if _, err := inFile.Seek(int64(segLen), io.SeekCurrent); err != nil {
			return fmt.Errorf("error seeking past segment: %w", err)
		}
		scanned += int64(segLen)
		segmentCount++
	}

	// Compute the expected HMAC and compare in constant time.
	expectedTrailer, err := computeTrailerHMAC(macKey, salt, masterNonce, segmentCount)
	if err != nil {
		return fmt.Errorf("error computing trailer HMAC: %w", err)
	}
	if !hmac.Equal(storedTrailer, expectedTrailer) {
		return fmt.Errorf("authentication failed: file has been tampered with or wrong password")
	}

	// 4. Trailer verified. Seek back to the start of the payload and decrypt.
	payloadStart := int64(constants.SaltSize + constants.XNonceSize)
	if _, err := inFile.Seek(payloadStart, io.SeekStart); err != nil {
		return fmt.Errorf("error seeking to payload: %w", err)
	}

	prefix := fmt.Sprintf("Decrypting %s", filepath.Base(inputFile))
	var segmentCounter uint64
	var bytesRead uint64
	bytesRead += uint64(constants.SaltSize + constants.XNonceSize)
	totalBytes := uint64(totalFileSize)

	sizeBuf := make([]byte, 8)

	for segmentCounter < segmentCount {
		// 5. Read segment length
		if _, err := io.ReadFull(inFile, sizeBuf); err != nil {
			return fmt.Errorf("error reading segment length: %w", err)
		}
		bytesRead += 8

		segmentLen := binary.BigEndian.Uint64(sizeBuf)

		// Bounds check is repeated here even though the scan pass already
		// validated lengths, because seek-based scan and sequential read must
		// agree — a TOCTOU on a local file is not a realistic threat but being
		// explicit costs nothing.
		maxAllowed := uint64(constants.SegmentSize + aead.Overhead())
		if segmentLen > maxAllowed {
			return fmt.Errorf("security error: segment size %d exceeds limit", segmentLen)
		}

		ciphertext := make([]byte, segmentLen)
		if _, err := io.ReadFull(inFile, ciphertext); err != nil {
			return fmt.Errorf("error reading ciphertext: %w", err)
		}
		bytesRead += segmentLen

		// 6. Derive unique nonce for this segment — must mirror the encryption path.
		nonce, err := deriveSegmentNonce(masterNonce, segmentCounter)
		if err != nil {
			return fmt.Errorf("error deriving segment nonce: %w", err)
		}

		// 7. Reconstruct AAD for authentication.
		plaintextLen := uint64(len(ciphertext)) - uint64(aead.Overhead())
		aad := make([]byte, 16)
		binary.BigEndian.PutUint64(aad[:8], segmentCounter)
		binary.BigEndian.PutUint64(aad[8:], plaintextLen)

		plaintextSegment, err := aead.Open(nil, nonce, ciphertext, aad)
		if err != nil {
			// This should not be reachable given the trailer HMAC already passed,
			// but is retained as a defence-in-depth layer.
			return fmt.Errorf("authentication failed: segment %d rejected", segmentCounter)
		}

		if _, err := outFile.Write(plaintextSegment); err != nil {
			return fmt.Errorf("error writing plaintext: %w", err)
		}

		segmentCounter++

		if totalBytes > 0 {
			cryptoutils.RunProgressBar(prefix, int((bytesRead*100)/totalBytes))
		}
	}

	cryptoutils.RunProgressBar(prefix, 100)
	fmt.Println()

	succeeded = true
	return nil
}

// ExpandInputPaths resolves multiple input paths and glob patterns,
// and filters out directories. Files that do not match the expected extension
// for the given operation are skipped with a warning rather than silently,
// so the user is never left wondering why a file was ignored.
func ExpandInputPaths(inputs []string, operation string) ([]string, error) {
	var files []string

	for _, input := range inputs {
		// Step 1: check if input is a literal file path.
		info, err := os.Stat(input)
		if err == nil {
			if !info.IsDir() {
				ext := strings.ToLower(filepath.Ext(info.Name()))
				// Parentheses make the compound condition explicit and unambiguous.
				// Without them the precedence of && vs || is easy to misread.
				if (operation == "encrypt" && ext != ".cfo") || (operation == "decrypt" && ext == ".cfo") {
					files = append(files, input)
				} else {
					// Warn rather than silently skip so the user knows the file
					// was seen but excluded.
					fmt.Fprintf(os.Stderr, "warning: skipping %q (wrong extension for %s)\n", input, operation)
				}
			}
			continue
		}

		// Step 2: treat as glob pattern if the literal path does not exist.
		matches, err := filepath.Glob(input)
		if err != nil {
			return nil, fmt.Errorf("invalid pattern %q: %w", input, err)
		}

		if len(matches) == 0 {
			fmt.Fprintf(os.Stderr, "warning: pattern %q matched no files\n", input)
			continue
		}

		for _, match := range matches {
			info, err := os.Stat(match)
			if err != nil {
				continue
			}
			if !info.IsDir() {
				ext := strings.ToLower(filepath.Ext(info.Name()))
				if (operation == "encrypt" && ext != ".cfo") || (operation == "decrypt" && ext == ".cfo") {
					files = append(files, match)
				} else {
					fmt.Fprintf(os.Stderr, "warning: skipping %q (wrong extension for %s)\n", match, operation)
				}
			}
		}
	}

	if len(files) == 0 {
		return nil, fmt.Errorf("no valid input files found")
	}

	return files, nil
}
